vich_uploader:
    db_driver: orm

    mappings:
        project_file:
            uri_prefix: /project
            upload_destination: '%upload_directory%'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
