vich_uploader:
    db_driver: orm

    mappings:
        project_file:
            uri_prefix: /project
            upload_destination: '%upload_directory%/documents/projects'
        avatar_image:
            uri_prefix: /images
            upload_destination: '%upload_directory%/images/avatar'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true;
            delete_on_remove: true;
